services:
  database_aisam:
    image: postgres
    container_name: database_aisam
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Lc_150595
      - POSTGRES_DB=database_aisam
    volumes:
      - pgdata:/data/postgres

  app:
    build:
      context: .
      target: development
    container_name: aisam.com.br
    command: npm run dev
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
    links:
      - database_aisam
    depends_on:
      - database_aisam

volumes:
    pgdata:
        driver: local

