// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prjckokcquytvdgkgndw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByamNrb2tjcXV5dHZkZ2tnbmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzY1ODIsImV4cCI6MjA3MDE1MjU4Mn0.YniCRjhQVDnefEocm8oPAYundGNy4C5dzvZOeESKzwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});